[workspace]
channels = ["robostack-humble", "conda-forge"]
name = "ro47007_mirte_ws"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.1"

[tasks]
fetch = {cmd = "vcs import --input repos.repos src", description = "Fetch MIRTE packages"}
build = {cmd = "colcon build --symlink-install", description = "Build the ROS workspace"}
ws-clean = {cmd = "rm -rf build install log", description = "Clean build artifacts (build, install, log directories)"}
clean-build = [{ task = "ws-clean" }, { task = "build" }]

[dependencies]
# Base ROS dependencies
ros-humble-ros-base = "*"
pkg-config = "*"
compilers = "*"
make = "*"
ninja = "*"
ros-humble-ros2cli = "*"

# Build tools
colcon-common-extensions = "*"
#cmake = "<4"

# Workspace dependencies
ros-humble-ament-cmake = "*"
ros-humble-ament-cmake-auto = "*"
ros-humble-ament-cmake-gtest = "*"
ros-humble-ament-lint-auto = "*"
ros-humble-ament-lint-common = "*"
ros-humble-backward-ros = "*"
ros-humble-control-toolbox = "*"
ros-humble-controller-manager = "*"
ros-humble-diff-drive-controller = "*"
ros-humble-effort-controllers = "*"
ros-humble-filters = "*"
ros-humble-forward-command-controller = "*"
ros-humble-gazebo-dev = "*"
ros-humble-gazebo-plugins = "*"
ros-humble-gazebo-ros = "*"
ros-humble-gazebo-ros-pkgs = "*"
ros-humble-gazebo-ros2-control = "*"
ros-humble-geometry-msgs = "*"
ros-humble-hardware-interface = "*"
ros-humble-joint-state-broadcaster = "*"
ros-humble-joint-state-publisher = "*"
ros-humble-joint-state-publisher-gui = "*"
ros-humble-joint-trajectory-controller = "*"
# NOTE: unused, need to update mirte_description to use this
ros-humble-mecanum-drive-controller = "*"
ros-humble-moveit-configs-utils = "*"
ros-humble-moveit-kinematics = "*"
ros-humble-moveit-planners = "*"
ros-humble-moveit-ros-move-group = "*"
ros-humble-moveit-ros-visualization = "*"
ros-humble-moveit-setup-assistant = "*"
ros-humble-moveit-simple-controller-manager = "*"
ros-humble-nav-msgs = "*"
ros-humble-pluginlib = "*"
ros-humble-rclcpp = "*"
ros-humble-rclcpp-lifecycle = "*"
ros-humble-robot-state-publisher = "*"
ros-humble-ros2-controllers = "*"
ros-humble-ros2-controllers-test-nodes = "*"
ros-humble-ros2controlcli = "*"
ros-humble-ros2launch = "*"
ros-humble-rosidl-default-generators = "*"
ros-humble-rosidl-default-runtime = "*"
ros-humble-rviz-common = "*"
ros-humble-rviz-default-plugins = "*"
ros-humble-rviz2 = "*"
ros-humble-sensor-msgs = "*"
ros-humble-std-msgs = "*"
ros-humble-std-srvs = "*"
ros-humble-teleop-twist-keyboard = "*"
ros-humble-tf2 = "*"
ros-humble-tf2-ros = "*"
ros-humble-trajectory-msgs = "*"
ros-humble-twist-mux = "*"
#ros-humble-twist-stamper = "*"
ros-humble-xacro = "*"
ros-humble-yaml-cpp-vendor = "*"
ros-humble-rqt = "*"
ros-humble-rqt-common-plugins = "*"
ros-humble-image-transport = "*"
ros-humble-slam-toolbox = ">=2.6.10,<3"
ros-humble-navigation2 = ">=1.1.20,<2"
ros-humble-nav2-bringup = ">=1.1.20,<2"
ros-humble-nav2-map-server = ">=1.1.20,<2"
ros-humble-tf2-tools = ">=0.25.19,<0.26"
ultralytics = ">=8.4.61,<9"
pip = ">=26.1.2,<27"

[activation]
#scripts = ["install/setup.bash"]

[pypi-dependencies]
vcstool = ">=0.3.0, <0.4"
cmake = "==3.22.1"

[activation.env]
GAZEBO_SUPPRESS_EOL_WARNING = "1"
ROS_LOCALHOST_ONLY = "0"
